### ISSUE TITLE
Unable to record a sound using the "whileRecordingASound" method

### ISSUE THREAD

**Issue by libetl** [libetl/soundtransform#59]
Byte buffer not big enough, java.nio.BufferOverflowException
at java.nio.Buffer.checkPutBounds(Buffer.java:183)
at java.nio.ByteArrayBuffer.put(ByteArrayBuffer.java:266)
at org.toilelibre.libe.soundtransform.infrastructure.service.record.exporter.ByteBufferExporter.export(ByteBufferExporter.java:23)
at org.toilelibre.libe.soundtransform.infrastructure.service.record.android.AndroidRecorderThread.writeAudioDataToFile(AndroidRecorderThread.java:67)
at org.toilelibre.libe.soundtransform.infrastructure.service.record.android.AndroidRecorderThread.run(AndroidRecorderThread.java:38)

**Comment by libetl** [comment]
I found the cause, but I don't know why this call returns a bad value : AudioRecord.getMinBufferSize

**Comment by libetl** [comment]
Doubled the value, seems ok but don't understand why
